def SetAvatars(info):
    info.PlayerAvatars.Add("player_avatars/A01.png");
    info.PlayerAvatars.Add("player_avatars/A02.png");
    info.PlayerAvatars.Add("player_avatars/A03.png");
    info.PlayerAvatars.Add("player_avatars/A04.png");
    info.PlayerAvatars.Add("player_avatars/A05.png");
    info.PlayerAvatars.Add("player_avatars/B01.png");
    info.PlayerAvatars.Add("player_avatars/B02.png");
    info.PlayerAvatars.Add("player_avatars/B03.png");
    info.PlayerAvatars.Add("player_avatars/B04.png");
    info.PlayerAvatars.Add("player_avatars/B05.png");
    info.PlayerAvatars.Add("player_avatars/C01.png");
    info.PlayerAvatars.Add("player_avatars/C02.png");
    info.PlayerAvatars.Add("player_avatars/C03.png");
    info.PlayerAvatars.Add("player_avatars/C04.png");
    info.PlayerAvatars.Add("player_avatars/C05.png");
    info.PlayerAvatars.Add("player_avatars/D01.png");
    info.PlayerAvatars.Add("player_avatars/D02.png");
    info.PlayerAvatars.Add("player_avatars/D03.png");
    info.PlayerAvatars.Add("player_avatars/D04.png");
    info.PlayerAvatars.Add("player_avatars/D05.png");
    info.PlayerAvatars.Add("player_avatars/E01.png");
    info.PlayerAvatars.Add("player_avatars/E02.png");
    info.PlayerAvatars.Add("player_avatars/E03.png");
    info.PlayerAvatars.Add("player_avatars/E04.png");
    info.PlayerAvatars.Add("player_avatars/E05.png");
    info.PlayerAvatars.Add("player_avatars/F01.png");
    info.PlayerAvatars.Add("player_avatars/F02.png");
    info.PlayerAvatars.Add("player_avatars/F03.png");
    info.PlayerAvatars.Add("player_avatars/F04.png");
    info.PlayerAvatars.Add("player_avatars/F05.png");
    info.PlayerAvatars.Add("player_avatars/FA01.png");
    info.PlayerAvatars.Add("player_avatars/FA02.png");
    info.PlayerAvatars.Add("player_avatars/FA03.png");
    info.PlayerAvatars.Add("player_avatars/FA04.png");
    info.PlayerAvatars.Add("player_avatars/FA05.png");
    info.PlayerAvatars.Add("player_avatars/FB01.png");
    info.PlayerAvatars.Add("player_avatars/FB02.png");
    info.PlayerAvatars.Add("player_avatars/FB03.png");
    info.PlayerAvatars.Add("player_avatars/FB04.png");
    info.PlayerAvatars.Add("player_avatars/FB05.png");
    info.PlayerAvatars.Add("player_avatars/FC01.png");
    info.PlayerAvatars.Add("player_avatars/FC02.png");
    info.PlayerAvatars.Add("player_avatars/FC03.png");
    info.PlayerAvatars.Add("player_avatars/FC04.png");
    info.PlayerAvatars.Add("player_avatars/FC05.png");
    info.PlayerAvatars.Add("player_avatars/FD01.png");
    info.PlayerAvatars.Add("player_avatars/FD02.png");
    info.PlayerAvatars.Add("player_avatars/FD03.png");
    info.PlayerAvatars.Add("player_avatars/FD04.png");
    info.PlayerAvatars.Add("player_avatars/FD05.png");
    info.PlayerAvatars.Add("player_avatars/FE01.png");
    info.PlayerAvatars.Add("player_avatars/FE02.png");
    info.PlayerAvatars.Add("player_avatars/FE03.png");
    info.PlayerAvatars.Add("player_avatars/FE04.png");
    info.PlayerAvatars.Add("player_avatars/FE05.png");
    info.PlayerAvatars.Add("player_avatars/FG01.png");
    info.PlayerAvatars.Add("player_avatars/FG02.png");
    info.PlayerAvatars.Add("player_avatars/FG03.png");
    info.PlayerAvatars.Add("player_avatars/FG04.png");
    info.PlayerAvatars.Add("player_avatars/FG05.png");
    info.PlayerAvatars.Add("player_avatars/FH01.png");
    info.PlayerAvatars.Add("player_avatars/FH02.png");
    info.PlayerAvatars.Add("player_avatars/FH03.png");
    info.PlayerAvatars.Add("player_avatars/FH04.png");
    info.PlayerAvatars.Add("player_avatars/FH05.png");
    info.PlayerAvatars.Add("player_avatars/FI01.png");
    info.PlayerAvatars.Add("player_avatars/FI02.png");
    info.PlayerAvatars.Add("player_avatars/FI03.png");
    info.PlayerAvatars.Add("player_avatars/FI04.png");
    info.PlayerAvatars.Add("player_avatars/FI05.png");
    info.PlayerAvatars.Add("player_avatars/G01.png");
    info.PlayerAvatars.Add("player_avatars/G02.png");
    info.PlayerAvatars.Add("player_avatars/G03.png");
    info.PlayerAvatars.Add("player_avatars/G04.png");
    info.PlayerAvatars.Add("player_avatars/G05.png");
    info.PlayerAvatars.Add("player_avatars/H01.png");
    info.PlayerAvatars.Add("player_avatars/H02.png");
    info.PlayerAvatars.Add("player_avatars/H03.png");
    info.PlayerAvatars.Add("player_avatars/H04.png");
    info.PlayerAvatars.Add("player_avatars/H05.png");
    info.PlayerAvatars.Add("player_avatars/I01.png");
    info.PlayerAvatars.Add("player_avatars/I02.png");
    info.PlayerAvatars.Add("player_avatars/I03.png");
    info.PlayerAvatars.Add("player_avatars/I04.png");
    info.PlayerAvatars.Add("player_avatars/I05.png");
    info.PlayerAvatars.Add("player_avatars/J01.png");
    info.PlayerAvatars.Add("player_avatars/J02.png");
    info.PlayerAvatars.Add("player_avatars/J03.png");
    info.PlayerAvatars.Add("player_avatars/J04.png");
    info.PlayerAvatars.Add("player_avatars/J05.png");
    info.PlayerAvatars.Add("player_avatars/K01.png");
    info.PlayerAvatars.Add("player_avatars/K02.png");
    info.PlayerAvatars.Add("player_avatars/K03.png");
    info.PlayerAvatars.Add("player_avatars/K04.png");
    info.PlayerAvatars.Add("player_avatars/L05.png");
    info.PlayerAvatars.Add("player_avatars/L01.png");
    info.PlayerAvatars.Add("player_avatars/L02.png");
    info.PlayerAvatars.Add("player_avatars/L03.png");
    info.PlayerAvatars.Add("player_avatars/L04.png");
    info.PlayerAvatars.Add("player_avatars/L05.png");
    info.PlayerAvatars.Add("player_avatars/M01.png");
    info.PlayerAvatars.Add("player_avatars/M02.png");
    info.PlayerAvatars.Add("player_avatars/M03.png");
    info.PlayerAvatars.Add("player_avatars/M04.png");
    info.PlayerAvatars.Add("player_avatars/M05.png");
    info.PlayerAvatars.Add("player_avatars/N01.png");
    info.PlayerAvatars.Add("player_avatars/N02.png");
    info.PlayerAvatars.Add("player_avatars/N03.png");
    info.PlayerAvatars.Add("player_avatars/N04.png");
    info.PlayerAvatars.Add("player_avatars/N05.png");
    info.PlayerAvatars.Add("player_avatars/O01.png");
    info.PlayerAvatars.Add("player_avatars/O02.png");
    info.PlayerAvatars.Add("player_avatars/O03.png");
    info.PlayerAvatars.Add("player_avatars/O04.png");
    info.PlayerAvatars.Add("player_avatars/O05.png");
    return;


def SetGameInfo (info):
    info.GameStyle = "Testing_Game";
    tankInfo = info.NewOption("tank",0);
    tankInfo.Options.Add("Standard");
    info.PlayerModels.Add("IcoTank2");
    SetAvatars(info);
    return True;

def SetNewPlayerInfo (player):
    player.ModelID = 0;
    player.AvatarID = -1;
    return True;

def GetPlayerSpawn (player):
    return ServerAPI.GetStandardSpawn();